version: '3.8'

services:
  ollama:
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_OPENI_OLLAMA
    image: ollama/ollama:latest
    ports:
      - ${OLLAMA_OPENUI_PORT}:11434
    volumes:
      - ${OLLAMA_VOLUME_PATH:-ollama}:/root/.ollama

  backend:
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_OPENUI_BACKEND
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_OPENUI_PORT}:7878
    environment:
      - OLLAMA_HOST=ollama
      - OPENAI_API_KEY=${OPENAPI_KEY}
    depends_on:
      - ollama
volumes:
  ollama:
