apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.ollama.name }}-pv
  namespace: {{ .Values.global.namespace }}
spec:
  capacity:
    storage: {{ .Values.ollama.volumeSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.ollama.volumePath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ollama.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.volumeSize }}
